<a href="https://colab.research.google.com/github/govindakolli/Tasks_DataScience/blob/main/MatrixFactorizationUsingSVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Implementing Matrix Factorization using SVD**

Implementing matrix factorization using singular value decomposition (SVD) with numpy.

**A   =   U      S     V <sup>T<sup>**


**A <sub>mxn<sub>**   =   **U <sub>mxm<sub>**  **S <sub>mxn<sub>**    **V     <sub>nxn<sub>**




Perform Singular Value Decomposition (SVD) for matrix factorization.

    Parameters:
    matrix (numpy.ndarray): Input matrix (m x n).
    k (int): Number of singular values and vectors to keep.

    Returns:
    U (numpy.ndarray): Left singular vectors (m x k).
    S (numpy.ndarray): Singular values (k).
    Vt (numpy.ndarray): Right singular vectors (k x n).
    

In [6]:
import numpy as np

In [15]:
def matrix_factorization_svd(matrix, k):
    # Perform SVD
    U, S, Vt = np.linalg.svd(matrix, full_matrices=False)

    # Keep only the top k singular values and vectors
    U_k = U[:, :k]
    S_k = S[:k]
    Vt_k = Vt[:k, :]

    return U_k, S_k, Vt_k




In [16]:
# Example usage
if __name__ == "__main__":
    # Sample matrix
    matrix = np.array([[5, 4, 0, 0],
                       [3, 0, 0, 1],
                       [4, 0, 0, 5],
                       [0, 2, 3, 0],
                       [0, 0, 4, 4]])

    # Specify the number of singular values to keep
    k = 4  # Number of latent features

    # Perform SVD
    U, S, Vt = matrix_factorization_svd(matrix, k)

    # Print the results
    print("Original Matrix:\n", matrix)
    print("\nLeft Singular Vectors (U):\n", U)
    print("\nSingular Values (S):\n", S)
    print("\nRight Singular Vectors (Vt):\n", Vt)

    # Reconstruct the matrix (optional)
    reconstructed_matrix = np.dot(U, np.dot(np.diag(S), Vt))
    print("\nReconstructed Matrix:\n", reconstructed_matrix)

Original Matrix:
 [[5 4 0 0]
 [3 0 0 1]
 [4 0 0 5]
 [0 2 3 0]
 [0 0 4 4]]

Left Singular Vectors (U):
 [[-0.5448483  -0.6324143   0.38211012  0.20406773]
 [-0.31695486 -0.14433254 -0.17143399 -0.92106636]
 [-0.6693209   0.15018686 -0.51753854  0.3165948 ]
 [-0.13857339  0.14978823  0.699486   -0.08317108]
 [-0.36808545  0.73090879  0.25976034 -0.0533238 ]]

Singular Values (S):
 [8.73668712 6.14645616 4.67188274 1.03193339]

Right Singular Vectors (Vt):
 [[-0.72709364 -0.28117523 -0.21610731 -0.58785453]
 [-0.48716229 -0.36282383  0.54877148  0.57435323]
 [-0.14424711  0.6266023   0.67157066 -0.36817819]
 [-0.4617364   0.62981658 -0.44848672  0.43473007]]

Reconstructed Matrix:
 [[ 5.00000000e+00  4.00000000e+00  1.16738895e-15  2.05923857e-15]
 [ 3.00000000e+00  1.55484639e-15  4.78515334e-16  1.00000000e+00]
 [ 4.00000000e+00  1.00734896e-15  1.65097268e-16  5.00000000e+00]
 [ 1.38423187e-16  2.00000000e+00  3.00000000e+00  2.43253161e-16]
 [-6.46752961e-16 -1.08845069e-15  4.0000000

In [7]:
A = np.array([[4,4,3],[1,4,3],[4,8,1]])
U,S,Vt = np.linalg.svd(A)
print(A)

[[4 4 3]
 [1 4 3]
 [4 8 1]]


In [8]:
print(A.shape)

(3, 3)


In [9]:
print(U.shape)

(3, 3)


In [10]:
print(S.shape)

(3,)


In [11]:
print(Vt.shape)

(3, 3)


In [14]:
A = np.array([[4,4,3],[1,4,3],[4,8,1]])
#SVD
U,S,Vt = np.linalg.svd(A)
# matix sizes
print("Original Matrix",A)
print("U shape :",U.shape)
print("S shape :",S.shape)
print("Vt shape :",Vt.shape)
#matrix Mul
A_remade = U @ np.diag(S) @Vt

print("Reconstructed MAtrix :",A_remade)

Original Matrix [[4 4 3]
 [1 4 3]
 [4 8 1]]
U shape : (3, 3)
S shape : (3,)
Vt shape : (3, 3)
Reconstructed MAtrix : [[4. 4. 3.]
 [1. 4. 3.]
 [4. 8. 1.]]
