<a href="https://colab.research.google.com/github/govindakolli/Tasks_DataScience/blob/main/MovingAvgFunctonForNumpyArr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Custom Moving Average Function for NumPy Arrays**

Implement a moving average function for a numpy array with a specified window size.



In [ ]:
import numpy as np

In [ ]:
def custom_moving_average(arr,window_size):

    if window_size <= 0 :
      raise ValueError("Window size must be positive")

    if window_size > len(arr):
      raise ValueError("Window size should be less than array size")

    #creating empty moving average array
    moving_avg = np.empty(len(arr)- window_size + 1)

    #calculate moving avg
    for i in range(len(moving_avg)):
      moving_avg[i] = np.mean(arr[i:i + window_size])

    return moving_avg


In [ ]:
#sample data
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3
result = custom_moving_average(data, window_size)
print("Original array:", data)
print("Moving average:", result)

Original array: [1 2 3 4 5 6 7 8 9]
Moving average: [2. 3. 4. 5. 6. 7. 8.]


In [ ]:
#complexity
"""
O(n*w)
here n is array length and w is window size
"""

In [ ]:
def moving_average_2d(arr, window_size):

    if window_size <= 0:
        raise ValueError("Window size must be positive.")
    if window_size % 2 == 0:
        raise ValueError("Window size must be odd.")
    if window_size > arr.shape[0] or window_size > arr.shape[1]:
        raise ValueError("Window size must not be greater than the array dimensions.")

    n = window_size // 2  # Half window size
    rows, cols = arr.shape
    moving_avg = np.empty((rows - n * 2, cols - n * 2))  # Output size

    # Calculate the moving averages
    for i in range(n, rows - n):
        for j in range(n, cols - n):
            moving_avg[i - n, j - n] = np.mean(arr[i - n:i + n + 1, j - n:j + n + 1])

    return moving_avg



In [ ]:
# Example usage
data = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10],
                 [11, 12, 13, 14, 15],
                 [16, 17, 18, 19, 20],
                 [21, 22, 23, 24, 25]])

window_size = 3  # Should be odd
result = moving_average_2d(data, window_size)
print("Original array:\n", data)
print("Moving average:\n", result)

Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Moving average:
 [[ 7.  8.  9.]
 [12. 13. 14.]
 [17. 18. 19.]]
